### ISSUE TITLE
Error when trying to run `OSCproxy.py`

### ISSUE THREAD

**Issue by Brian-Campuzano** [CUBoulder-2017-IML4HCI/eeg_hand#1]
![error_operation_successful](https://cloud.githubusercontent.com/assets/5853878/23155447/79dd595c-f7c7-11e6-9f7b-21c56f91ebfe.jpg)

**Comment by RyanBRiley** [comment]
![denied](https://cloud.githubusercontent.com/assets/3384967/23195041/0647e4be-f86f-11e6-8d1d-d8c01f8ad367.jpg)
